spring:
  datasource:
#    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://localhost:3406/chs?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    url: jdbc:p6spy:mysql://127.0.0.1:3406/chs?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&useSSL=false&zeroDateTimeBehavior=convertToNull
    username: root
    password: 491300
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
      auto-commit: true
      idle-timeout: 30000
      pool-name: CHSlog-HikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
  security:
    user:
      name: kitten
      password: 123456

minio:
  endpoint: http://127.0.0.1:9000
  accessKey: kitten
  secretKey: 467300aA
  bucketName: chs

alipay:
  # 支付宝开放平台秘钥工具获取
  app-id: 9021000145622833
  private-key: MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDE15KWQ+v2E7G+BQqVIAYBM9DM0Z2kpVtgcxaaL3xrYrZzdiG/kgdA4L/iTE048qWy1uaMHpo6yFCCOuJ8Iy7WJWGDeBDEyqqr8fXeKgzoBa9ljZE1FJe1tMmnQyBIpSG8zU4s8+//p1ZsPCWfeE6HpXykFD4yDjymEzfPGdesGr02eZHkO31A49y3Yn2tGLHSVQ6ksAUKubbspYfBgbgGABV1UnHzMC1C5OwxWBy65iXiz0RikO8jFlVt3VejUEIXURbPCFEsIBCpee/OnixjKthUqVlpOYTgv4c4Gfr6+k1rv+K5fGJOs1uR9WnHDnDLHVykab/F4njHeyrSx1TrAgMBAAECggEAN34+yTYk058BwPxS22/HwZcGCngd5Ujo1ewcNyOkA/I0VaC8KvHUMaoq7nVsX92ocR68qEwIVwIaEFzhdPXGQoEPWK0ErTYln4v7MMLSGKdhp1Od2EUR8BwjrY/zDgff1wZaP7oVsxFN//2E7cxQ91TkKq26SwpQdtF8LlquvsnbeECMsc971HDeWzFRW51CbWXu/hKO4U2wILiClyzrwtiAY8EXtAfXJqPPoTwyRdSMirB3aVK6c2OULxoVMM2L9JVHvzGzRAW2EEbcHqXmVRIWHorNG+h4Wv5LidLsj9dLrtMbiAuYHCikKueyWk1zkV+FxYAPZwCMIupI83TEYQKBgQD+PJg+pRBpxm6Xx0nRmWvMpUy9t0/bEwQyfWanZD/ijq6zSy5aPG6RCCfkHe4zGbbIhcl7lRzUop9laKPepeZEGq2L3OMmsG4QjmCMa5jWYVUdcMwRgCu8oR1Y2vBCSwyKLEzJRsn1R6HV3bkKuDl7e13uQdolweBvPbvKFCdfdwKBgQDGNRJqxNi/9ODcy/cFy0/PsLaPuMHq16qicMnjMfp2o9/jIYej603JedMO/T8wJ8TdH+B0lv+NMtgLh1OvCwKeBQvKEP7x+6dw64iBoIM+d2/tworQ4Q0O3X9lSWXu9rTLT22iod/QvMp3FB6z0+tvJepzlKNgDlE/v9zPPAYbLQKBgQCCk6SuKCEx8pTCp7ymRmIzjYLIvenp3u588CNVPgwB1L6tn6OC/R7cpo+2fhjlbgOPIgfFzWQtYgj0ELZ5mEOYHwubliukp2EgZ7/23xx0nzEUGeb15hqQmz9zb5+OrPUX0oDtr8nyjIP2UBbGBrCfV1F7GZ9tXRJkkBRvScKfKQKBgEtrHFPmDPeVjQ5Wyeq5fufvPLgZPChI4dOniRpbBQuptWIuevdDbLjSEx4r/KQtLbpaC8UxQ5INm6lfV9dOIDPShbbgmrGm6QKNjMaONgJJ3hwhH0L1r0tNutDmidPQqeCGm5f7cjdx7rQ6wqf4ZihHzBsonrXJHN9d+P4dv9ENAoGAbw1WUmC3Z8hoMIrAvGaQ6lyADU2D+yWCmIQ+8IlB4ReA3UcH5DA3lLaOLpAGcXhT5e9km2XnAscfyS21QStWFbo7CY1In/EeBgi8K6AeMqxcUVExzk4MHMqYGMsY1KRnsgrfFi6UgZQh67ZUiYQWE3Abfr+wnLx8oew5SWcgSck=
  public-key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAuKWYjcx2PGXKsf8pJlaUMwT23Gr5fXolsGRm6Lo6cqTUHq6y1+ivfZw3DSC1xmPeuKcOi4JAYGuumExWojEc8i/DTPWqnjPwikNBcf5J6vHGr8WM+qenUvL+Rb43gJZjMcFgsAaKnQYfPIrDW4ysrGPX1PtgWojiPQRCvJNWXHD/9CfS+pqsfFoNwMMVBIFrkB/xNCVMbejG0jHYdnmzm6cXutVy0vr15eihV/WYDB7o5x6+s38br32HAanO0s9dPecvfrjygInTb6USdgNkCwc/nzXeoaxEtPqxasjr90pPVx6GW00lfBI1/Dxp9H/M3pxtAq5sHLduY48uUlwTXQIDAQAB
  gateway-url: https://openapi-sandbox.dl.alipaydev.com/gateway.do  # 沙箱接口
  notify-url: https://6d647276.r33.cpolar.top/recharge/notify  # 回调接口
  return-url: http://localhost:5173/#/recharge/result # 商户界面

