server:
  port: 9200

spring:
  profiles:
    active: dev
#    active: prod # 测试环境下将日志输出到文件 ./log/date.log
#  jackson:
#    default-property-inclusion: non_null
#    date-format: yyyy-MM-dd HH:mm:ss

jjwt:
  issuer: kitten
  secret: gL8WRefQk52Lm9WRj2+Ij2VEYLgg1vz4EyTfXjgWSuhQGAnchSKJBZdma+qf89oVbR3NYOgvd2l42+FoCWjFXw==
  tokenPrefix: Bearer
  tokenHeaderKey: Authorization
  tokenExpireTime: 14400

mybatis-plus:
  mapper-locations:
    - classpath*:/mapper/**/*.xml
